### ISSUE TITLE
Position adjustment

### ISSUE THREAD

**Issue by OlegCheban** [OlegCheban/WaterMarkIt#17]
Sometimes, we need a watermark to be near another one. For instance, we might need two watermarks to be at the center, with the second one located below the first.

```java
.position(WatermarkPosition.CENTER).adjust(int x, int y)
```
The method adjust is closely coupled with position method. It must be accessible only after the position has been specified.

**Comment by v-perfilev** [comment]
Salut @OlegCheban! I've worked a lot with Apache pdfbox before and can add this feature. Can you assign the issue to me?

**Comment by OlegCheban** [comment]
> Salut @OlegCheban! I've worked a lot with Apache pdfbox before and can add this feature. Can you assign the issue to me?

Sure! I'll assign the issue to you. Thanks for volunteering to work on it!

**Comment by v-perfilev** [comment]
@OlegCheban, take a look at my PR. Is this what was needed? :-)

**Comment by OlegCheban** [comment]
> @OlegCheban, take a look at my PR. Is this what was needed? :-)

Looks good, let's merge it! Everything looks perfect. Excellent contribution! Thanks.
